server:
  port: 80
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 150MB
      max-request-size: 150MB

  application:
    name: yx-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
zuul:
##  prefix: /yx # 添加路由前缀
  retryable: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
#  routes:
#    yx-server:
#     path: /** # 将访问路径映射到/yx/**
#     serviceId: yx-server
#     sensitiveHeaders: "*"
  strip-prefix: false
ribbon:
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
